### ISSUE TITLE
Remove dependency on Express?

### ISSUE THREAD

**Issue by blakeembrey** [felixfbecker/typed-body-parser#1]
For instance, I've definitely used it a number of times with raw HTTP routers.

**Comment by felixfbecker** [comment]
Could you give me a short snippet for the tests? I would then add express as `devDependency` to verify that it works with express and raw http.

**Comment by blakeembrey** [comment]
Will do. For reference later (https://github.com/mulesoft/osprey/blob/master/lib/security/handler.js#L100).

**Comment by blakeembrey** [comment]
Thanks! 👍
